version: "3.9"

services:
  rabbitmq:
       image: rabbitmq:3.9-management
       container_name: 'rabbitmq_authservice'
       ports:
           - 5672:5672
           - 15672:15672
       volumes:
           - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
           - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
  api:
    container_name: 'auth_api_isolated'
    build: .
    ports:
      - "5000:80"
    depends_on:
      - db
      - rabbitmq
  db:
   container_name: 'auth_db_isolated'
   image: mysql:5.7
   restart: always
   environment:
       MYSQL_DATABASE: 'db'
       MYSQL_USER: 'user'
       MYSQL_PASSWORD: 'password'
       MYSQL_ROOT_PASSWORD: 'password'
   ports:
     - '3306:3306'
   volumes:
     - my-db:/var/lib/mysql
volumes:
  my-db: